{"name": "test_example[chromium]", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://www.tuoyucloud.com/train_test/#/login\", waiting until \"load\"", "trace": "page = <Page url='https://www.tuoyucloud.com/train_test/#/login'>\n\n    def test_example(page: Page) -> None:\n>       page.goto(\"https://www.tuoyucloud.com/train_test/#/login\")\n\ntestcases/test_AFCC.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../test/.venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:8667: in goto\n    self._sync(\n../test/.venv/lib/python3.8/site-packages/playwright/_impl/_page.py:500: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n../test/.venv/lib/python3.8/site-packages/playwright/_impl/_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n../test/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x7f9eee1e0ee0>\ncb = <function Channel.send.<locals>.<lambda> at 0x7f9eee1dedc0>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE           navigating to \"https://www.tuoyucloud.com/train_test/#/login\", waiting until \"load\"\n\n../test/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: TimeoutError"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1718444989963, "stop": 1718445019969, "uuid": "6c6b4af7-157d-4b51-a4c6-4265cf76d5f7", "historyId": "edc126a4bdf151c241bb3b8944e6df5f", "testCaseId": "29c989f11eac4358ab914c0336e0f34f", "fullName": "testcases.test_AFCC#test_example", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_AFCC"}, {"name": "host", "value": "192.168.5.41"}, {"name": "thread", "value": "26232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_AFCC"}]}